### ISSUE TITLE
Warns about self

### ISSUE THREAD

**Issue by Awk34** [nodesecurity/grunt-nsp-package#11]
The grunt task warns me about `grunt-nsp-package` having a vulnerable dependency to `semver` (https://nodesecurity.io/advisories/semver_redos).

**Comment by bear** [comment]
@Awk34 thanks for the report!

We are moving a lot of the functionality for nodesecurity into an new tool but it's not yet ready for public viewing. Once it is I'll post an update here so you can be aware of it.

thanks!

**Comment by Awk34** [comment]
:+1: thanks!

**Comment by bear** [comment]
fixed in PR #12
