### ISSUE TITLE
npmjs lists 0.0.5 as the latest release

### ISSUE THREAD

**Issue by plynchnlm** [nodesecurity/grunt-nsp-package#14]
...which leads to confusion.  The [github](https://github.com/nodesecurity/grunt-nsp-package) page says that if you run "npm install grunt-nsp-package --save-dev" you will have a task called "nsp-audit", but actually what that does is grab version 0.0.5 which defines a task "validate-package".

**Comment by evilpacket** [comment]
I'd suggest migrating to grunt-requiresafe as this package is likely to be deprecated in the very near future. Mostly as it's pretty much unmaintained and horrible to work on given how the rest of the nsp tools are structured.

requiresafe provides more accurate results and more performant responses, especially for checking packages with huge dep trees.

**Comment by plynchnlm** [comment]
In that case, it would be helpful if https://nodesecurity.io/tools mentioned requireSafe.  I will give it a try.
