### ISSUE TITLE
Missing support for git and custom npm registry

### ISSUE THREAD

**Issue by abtris** [nodesecurity/grunt-nsp-package#15]
```
Warning: Error: Not found : @apiaryio
Warning: Git dependency [difflet@git://github.com/apiaryio/difflet.git#master] ignored.
```

**Comment by evilpacket** [comment]
I'll add this to the list of potential features for grunt-requiresafe. 

We recommend migrating to that task as it's way more performant and accurate. grunt-nsp-package is likely to be deprecated in the near future.

**Comment by abtris** [comment]
ok, but nsp project is completely different thant requiresafe?

**Comment by bear** [comment]
Node Security Project's code bits are going to be handled by the open source parts of requireSafe
