### ISSUE TITLE
Readme and real world usage disagree

### ISSUE THREAD

**Issue by lloydwatkin** [nodesecurity/grunt-nsp-package#16]
In your readme you say that the grunt task is `nsp-audit` (https://github.com/nodesecurity/grunt-nsp-package/blob/master/README.md#options), but when attempting to use the library I needed to use `validate-package` (https://github.com/node-xmpp/node-xmpp-client/blob/master/Gruntfile.js#L83)

**Comment by bear** [comment]
@lloydwatkin you may want to consider using https://github.com/requiresafe/grunt-requiresafe instead - I know they were talking about eventually replacing NSP command line tools with the requireSafe ones. All of this we being worked on last week IIRC so it may not have officially happened yet.

**Comment by evilpacket** [comment]
Thanks @bear, yup these will get the deprecated flag soon and are replaced by the requiresafe versions.

**Comment by lloydwatkin** [comment]
Thanks @bear + @evilpacket, I'll switch projects to `requireSafe` as I get a chance.
