### ISSUE TITLE
Error handling of the http get call is insufficient

### ISSUE THREAD

**Issue by pavelfomin** [nodesecurity/grunt-nsp-package#9]
If the `http get` for `https://nodesecurity.io/validate/` fails for any reason (e.g. blocked by firewall, timeout, etc) then no errors are reported, grunt call returns 0 status and the message `No vulnerable modules found` is displayed.

Also, assuming that empty response as the indication of `no vulnerabilities found` is not the best practice. A better approach would be to return a successful json response.

This issue can be easily reproduced by pointing `nodesecurity.io` somewhere else in local /etc/hosts file:
127.0.0.1       nodesecurity.io

**Comment by bear** [comment]
@nlf my thinking is that this may have been fixed - can you look into it?

**Comment by nlf** [comment]
i'll take a look and confirm

**Comment by nlf** [comment]
not fixed, this line for sure is a problem: https://github.com/nodesecurity/nsp/blob/master/lib/auditPackage.js#L95

and i didn't bother tracing past that, since it's obviously broken.

**Comment by evilpacket** [comment]
I'd suggest migrating to grunt-requiresafe as this package is likely to be deprecated in the very near future. It should address this particular issue as well.

grunt-nsp-package is pretty much unmaintained and horrible to work on given how the rest of the nsp tools are structured.

requiresafe provides more accurate results and more performant responses, especially for checking packages with huge dep trees.
